name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    container: debian:10

    steps:
    - uses: actions/checkout@v4
    - run: apt update
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libblas-dev libboost-dev libarmadillo-dev libopenblas-dev cmake gcc make build-essential curl
        version: 1.0 
    - name: libarmadillo
      run: |
        cd /tmp/ 
        curl -X GET -L -o libarmadillo.tar.xz https://sourceforge.net/projects/arma/files/armadillo-12.8.4.tar.xz/download 
        tar -xJf /tmp/libarmadillo.tar.xz 
        cd armadillo-12.8.4
        mkdir build 
        cd build 
        cmake -D OPENBLAS_PROVIDES_LAPACK=true .. 
        make -j 2
        make install
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
    - name: make
      run: make CC=ccache -j 16
    - uses: actions/upload-artifact@v4
      with:
        name: Molspin Executable
        path: molspin
