name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    container: ubuntu:20.04

    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: |
        sed --in-place --regexp-extended "s/(\/\/)(archive\.ubuntu)/\1de.\2/" /etc/apt/sources.list
        ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime 
        apt update
        DEBIAN_FRONTEND=noninteractive apt install -y liblapack-dev libblas-dev libboost-dev libarmadillo-dev libopenblas-openmp-dev cmake gcc libstdc++-10-dev make build-essential curl
    - name: libarmadillo
      run: |
        cd /tmp/ 
        curl -X GET -L -o libarmadillo.tar.xz https://sourceforge.net/projects/arma/files/armadillo-12.8.4.tar.xz/download 
        tar -xJf /tmp/libarmadillo.tar.xz 
        cd armadillo-12.8.4
        mkdir build 
        cd build 
        cmake .. 
        make -j 2
        make install
    - name: cache-build
      id: cache-build
      uses: actions/cache@v4
      with:
        path: build
        key: build
    - name: make
      run: make -j 2
    - uses: actions/upload-artifact@v4
      with:
        name: Molspin Executable
        path: molspin
