name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    container: centos:8

    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: |
        yum install -y cmake gcc make curl openblas-openmp
    - name: libarmadillo
      run: |
        cd /tmp/ 
        curl -X GET -L -o libarmadillo.tar.xz https://sourceforge.net/projects/arma/files/armadillo-12.8.4.tar.xz/download 
        tar -xJf /tmp/libarmadillo.tar.xz 
        cd armadillo-12.8.4
        mkdir build 
        cd build 
        cmake .. 
        make -j 2
        make install
    - name: cache-build
      id: cache-build
      uses: actions/cache@v4
      with:
        path: build
        key: build
    - name: make
      run: make -j 16
    - uses: actions/upload-artifact@v4
      with:
        name: Molspin Executable
        path: molspin
