name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: debian:10

    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: |
        ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime 
        apt update
        DEBIAN_FRONTEND=noninteractive apt install -y libblas-dev libboost-dev libarmadillo-dev libopenblas-dev cmake gcc make build-essential curl
    - name: libarmadillo
      run: |
        cd /tmp/ 
        curl -X GET -L -o libarmadillo.tar.xz https://sourceforge.net/projects/arma/files/armadillo-12.8.4.tar.xz/download 
        tar -xJf /tmp/libarmadillo.tar.xz 
        cd armadillo-12.8.4
        mkdir build 
        cd build 
        cmake -D OPENBLAS_PROVIDES_LAPACK=true .. 
        make -j 2
        make install
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
    - name: make
      run: make CC="ccache g++ -std=c++17" -j 2
    - uses: actions/upload-artifact@v4
      with:
        name: Molspin Executable
        path: molspin
