name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: cache-build
      id: cache-build
      uses: actions/cache@v4
      with:
        path: build
        key: build
    - name: make
      run: make -j 16
    - uses: actions/upload-artifact@v4
      with:
        name: Molspin Executable
        path: molspin
