name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ghcr.io/das0mann/molspin:dockerenv

    steps:
    - uses: actions/checkout@v4
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
    - name: make
      run: make CC="ccache g++ -std=c++17" -j 16
    - uses: actions/upload-artifact@v4
      with:
        name: Molspin Executable
        path: molspin

  deploy:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: Molspin Executable
      - shell: bash
        run: cp molspin /data/lxd/viking_programs/molspin/molspin-test